"""
Author: Sergi Mas-Pujol
Last update: 12/11/2022

Utility to remove .pyc files generated by Pylin
"""

import os


def remove_pyc_files(main_ir):
    """ Remove all .pyc files """
    if not os.path.isdir(main_ir):
        raise ValueError(main_ir, "is not a valis directory")
    for subdir, _, files in os.walk(main_ir):
        for file in files:
            origin_file = os.path.join(subdir, file)
            if origin_file.endswith(".pyc"):
                print(origin_file)
                os.remove(origin_file)
